---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - '386'
      - arm
    ignore:
      - goos: darwin
        goarch: '386'

  - id: windows
    env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
    flags:
      - -trimpath
    goos:
      - windows
    goarch:
      - amd64

archives:
  - id: default
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    ids:
      - default
      - macOS
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

  - id: windows
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    ids:
      - windows
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "💥 Breaking Changes"
      regexp: "^.*[(\\w)]*!:+.*$"
      order: 50
    - title: "🚀 New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "🐛 Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "📦 Dependency updates"
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "📚 Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: "🔧 Other work"
      order: 9999
